- .gitignore
- .travis.yml
- README.md
- requirements.txt
- skopt/tests/test_basics.py
This adds basic support for travis and running tests with `nose`
> Problem: No travis support

- examples/plot_1d_demo.py
- skopt/gp_opt.py
- skopt/tests/test_gp_opt.py
> Change output type to scipy.OptimizeResult type

- skopt/gp_opt.py
- skopt/tests/test_gp_opt.py
Nothing serious, just some code cleanup.
> Some cleanup

- examples/plot_1d_demo.py
- examples/plot_branin.py
- skopt/__init__.py
- skopt/gp_opt.py
> [MRG] cleanup gp_minimize, expose parameters

- skopt/gbt.py
- skopt/tests/test_gbt.py
This is a better name, addresses one comment from #26
> Rename GBTQuantiles to GradientBoostingQuantileRegressor

- skopt/__init__.py
- skopt/benchmarks.py
- skopt/dummy_opt.py
- skopt/gp_opt.py
- skopt/tests/test_dummy.py
- skopt/tests/test_gp_opt.py
- skopt/utils.py
> [MRG] Add more tests

- skopt/gp_opt.py
> [MRG] Make kernel tunable

- skopt/dummy_opt.py
- skopt/gp_opt.py
- skopt/tests/test_dummy_opt.py
- skopt/tests/test_gp_opt.py
Fixes https://github.com/MechCoder/scikit-optimize/issues/39
> Input output checks for acquistion and func to be optimized

- skopt/benchmarks.py
I cannot run nosetests otherwise (probably a Python 2 issue)
> Set encoding to UTF-8

- examples/plot_gbrt_minimize_1d.py
- examples/plot_gbrt_minimize_2d.py
- examples/plot_gp_minimize_1d.py
- examples/plot_gp_minimize_2d.py
> Fix broken examples

- skopt/parameter.py
- skopt/tests/test_parameter.py
This PR adds the shorthand `(lower, upper, prior)` for defining `Real` parameters. Also includes some cosmit changes.
> [MRG] Shorthand for prior of Real variables

- examples/plot_comparison.py
- examples/plot_gbrt_minimize_1d.py
- examples/plot_gbrt_minimize_2d.py
- examples/plot_gp_minimize_1d.py
- examples/plot_gp_minimize_2d.py
- examples/plot_random_vs_gp.py
- skopt/__init__.py
- skopt/dummy_opt.py
- skopt/gbrt_opt.py
- skopt/gp_opt.py
- skopt/parameter.py
- skopt/space.py
- skopt/tests/test_dummy_opt.py
- skopt/tests/test_gbrt.py
- skopt/tests/test_gbrt_opt.py
- skopt/tests/test_gp_opt.py
- skopt/tests/test_parameter.py
- skopt/tests/test_space.py
- skopt/utils.py
This is a work in progress towards #81.
> [MRG] Refactoring to use search space API

- skopt/learning/gbrt.py
- skopt/tests/test_gbrt.py
Exposing the base estimator for fun and profit.
Fixes #26
> [MRG] Expose base_estimator in GradientBoostingQuantileRegressor

- skopt/space.py
Follow up to https://github.com/scikit-optimize/scikit-optimize/pull/83
> Optimized transform

- skopt/tests/test_tree_opt.py
- skopt/tree_opt.py
This is a follow up to #91.
----
What would have happened if I had pushed these changes to the same branch as #91 used?
> Improved tests for forest_minimize

- examples/hyperparameter-optimisation.ipynb
> [MRG] Notebook on hyperparameter optimisation

- skopt/tests/test_gp_opt.py
- skopt/tests/test_tree_opt.py
> [MRG] Faster tests? 

- examples/plot_comparison.py
- examples/plot_gbrt_minimize_1d.py
- examples/plot_gbrt_minimize_2d.py
- examples/plot_gp_minimize_1d.py
- examples/plot_gp_minimize_2d.py
- examples/plot_random_vs_gp.py
Catching up the examples to the new API.
Looked into this to fix #135 but can't reproduce that bug.
This makes me think we should run these on travis. Otherwise they will keep being out of date :-/
> Fixup examples to use new parameter names

- skopt/dummy_opt.py
- skopt/tests/test_common.py
- skopt/tests/test_dummy_opt.py
- skopt/tests/test_gp_opt.py
- skopt/tests/test_space.py
- skopt/tests/test_tree_opt.py
Start checking that we stick to the correct return types. Where have we got defined APIs?
`Space().rvs()` -> `list of lists`. The `*_minimize()` functions return a result object.
> [WIP] Check return types/API conformity

- skopt/tests/test_common.py
- skopt/tree_opt.py
Fixes https://github.com/scikit-optimize/scikit-optimize/issues/106
> [MRG+1] Support LCB and PI to tree-based optimizers

- setup.py
Fixes #152 
Added a few more fields as well. Who is the author of skopt? What about "The scikit-optimize contributors"? Should we make an email address (what doe sklearn do for this?)?
> List packages for setup.py

- skopt/plots.py
- skopt/space.py
Create a scatter plot from a `OptimizeResult`.
Do you know how to make the top triangle vanish or something useful we could display there?
This is the output from a run on `hart6`:
> [MRG] Scatter plot matrix

- skopt/plots.py
> [MRG] Fix 2d partial dependence plots

- requirements.txt
Nose should not be required to build the project.
> Remove nose from dependencies

- skopt/learning/gbrt.py
- skopt/learning/tests/test_gbrt.py
- skopt/tree_opt.py
> [MRG+1] Support parallel fitting to GradientBoostingQuantileRegressor

- skopt/callbacks.py
- skopt/dummy_opt.py
- skopt/gp_opt.py
- skopt/tests/test_common.py
- skopt/tree_opt.py
- skopt/utils.py
Fixes https://github.com/scikit-optimize/scikit-optimize/issues/111
> [MRG] Add verbose flag and callback to *_minimize

- skopt/dummy_opt.py
- skopt/forest_opt.py
- skopt/gp_opt.py
I stumbled upon this while working on another PR
> [MRG+1] remove some unused imports and an unreachable return

- skopt/plots.py
It seems a bit weird to have a y axis that says "minimum after n calls" and then start with n=0.
> [MRG] Add one to x-axis for convergence plot

- README.md
- skopt/__init__.py
Help people getting started with an example in the README and webpage.
> [MRG] Adding a "Get started example" to the README

- skopt/space.py
- skopt/tests/test_space.py
closes #183 
the `__eq__` methods definitely could use some tests, I'll add those, but do the `__repr__` methods need tests as well?
> [MRG+1] added __repr__ and __eq__ for all Dimension classes and Space

- build_tools/circle/install.sh
Fixes https://github.com/scikit-optimize/scikit-optimize/issues/32 
I'm not completely sure how the timeout in Circle Ci works, so just to check.
> Execute notebooks as part of build

- examples/bayesian-optimization.ipynb
'clutter' is actually a synonym of 'litter'
> cluttered around the minimum -> clustered around the minimum

- build_tools/circle/install.sh
- circle.yml
- examples/bayesian-optimization.ipynb
- examples/hyperparameter-optimization.ipynb
Fixes #221
Remove deprecation warnings by changing our scoring parameter
names.
Try and handle the warning from matplotlib about building the
font cache.
> [MRG] Handle warnings

- README.md
- build_tools/circle/install.sh
- build_tools/travis/install.sh
- requirements.txt
- setup.py
- skopt/__init__.py
> [MRG] CI: switch to scikit-learn 0.18

- skopt/acquisition.py
- skopt/optimizer/base.py
- skopt/tests/test_acquisition.py
Fixes https://github.com/scikit-optimize/scikit-optimize/issues/191
> [MRG] Provide gradients to EI

- benchmarks/README.md
- benchmarks/bench_branin.py
- benchmarks/bench_hart6.py
Fixes https://github.com/scikit-optimize/scikit-optimize/issues/264
> Add benchmarks for function calls taken to reach minimum

- benchmarks/README.md
> Improve wording in benchmark/README

- skopt/optimizer/base.py
- skopt/optimizer/gp.py
- skopt/tests/test_gp_opt.py
Fixes https://github.com/scikit-optimize/scikit-optimize/issues/53
> [MRG+1] Parallelize n_restarts_optimizers

- skopt/learning/gaussian_process/gpr.py
> [MRG] precompute K_inv + documentation formatting

- build_tools/circle/install.sh
- build_tools/travis/install.sh
Let's see if the issue raised in #230 is now fixed.
> [MRG] Remove pyqt dependency

- skopt/optimizer/gp.py
Fixes https://github.com/scikit-optimize/scikit-optimize/issues/282
> Increase n_restarts_optimizer

- skopt/callbacks.py
- skopt/learning/gaussian_process/kernels.py
- skopt/learning/gaussian_process/tests/test_kernels.py
- skopt/optimizer/base.py
- skopt/optimizer/gbrt.py
- skopt/space/space.py
- skopt/space/transformers.py
- skopt/tests/test_callbacks.py
- skopt/tests/test_space.py
- skopt/utils.py
Clean up some pep8 warnings and additional tests.
Added an additional test and logic in `check_dimension` to get coverage
for raising the exception.
> [MRG] Fix pep8 compliance

- skopt/acquisition.py
- skopt/optimizer/base.py
- skopt/optimizer/optimizer.py
Fixes https://github.com/scikit-optimize/scikit-optimize/issues/294
> [MRG] Group acquisition function and acquisition optimizer arguments

- CHANGELOG.md
Housekeeping. Let me know what else I missed that we should highlight.
> [MRG] Add to the CHANGELOG for v0.4

- benchmarks/README.md
- skopt/optimizer/gp.py
- skopt/optimizer/optimizer.py
This implements the GP-Hedge acquisition function as described in Algorithm 2 of https://dslpitt.org/uai/papers/11/p327-hoffman.pdf 
The idea is given a number of acquisition functions, at every `tell` to choose the best acquisition function that gives the maximum gain.
> [MRG] Implement GP-Hedge acquisition function

- .travis.yml
- README.md
- setup.cfg
- skopt/__init__.py
- skopt/learning/forest.py
- skopt/learning/gbrt.py
Minor fixes and nitpicks for preparing v0.3 release.
Adds auto deployment directly from travis to pypi when we tag a new release.
Fixing up a few doc strings.
> [WIP] v0.3 nitpicks and tweaks

- skopt/optimizer/optimizer.py
- skopt/space/space.py
- skopt/tests/test_common.py
- skopt/tests/test_space.py
Minor tweaks and one bug fix. Should also increase coverage.
> [MRG] Fix some pep8 violations

- skopt/optimizer/base.py
- skopt/optimizer/optimizer.py
- skopt/space/space.py
- skopt/tests/test_common.py
- skopt/tests/test_optimizer.py
- skopt/tests/test_space.py
Fixes #315
Move the call to `create_result` to `Optimizer` so that we can use the plot tools we have with ask-and-tell.
> [MRG] Move creation of result object to `Optimizer` class

- skopt/learning/gaussian_process/kernels.py
- skopt/learning/gaussian_process/tests/test_kernels.py
Fixes https://github.com/scikit-optimize/scikit-optimize/issues/330
> [MRG] Fix gradient for HammingKernel computation

- skopt/learning/gaussian_process/gpr.py
- skopt/tests/test_gp_opt.py
Fixes https://github.com/scikit-optimize/scikit-optimize/issues/308
> FIX: gp_minimize fails for default values

- benchmarks/bench_ml.py
This is a continuation of https://github.com/scikit-optimize/scikit-optimize/pull/317 .
@MechCoder It seemed like the easiest solution was to just make a new fork of the repo and to copy the bench_ml.py file there. Otherwise I risk messing up things again with commits :)
> [MRG] Supervised Learning benchmark

- skopt/tests/test_utils.py
Fixes #316 
Added a test to check that the dump()ing and load()ing of `Optimizer` instances works., because "it would be a good idea" 😆 
cc @glouppe
> [MRG] Add test for dump()/load() of Optimizer class

- benchmarks/bench_ml.py
I did some code cleanup and fixed it for Python3
> Code cleanup of bench_ml.py

- CHANGELOG.md
- skopt/callbacks.py
- skopt/tests/test_callbacks.py
Follow up on #6 and #336. This adds a "stop if delta y of N best points is less than delta".
> [MRG] Add delta y early stopping callback

- skopt/optimizer/optimizer.py
the smallest PR ever [ci skip]
> DOC: small typo in Optimizer.tell

- AUTHORS.md
- CHANGELOG.md
Added @mirca and @iaroslav-ai to the list of contributors.
Can you think of something else we worked on that should be added to the changelog? We haven't been very good with making notes there as we go along.
> [MRG] Add new contributors and updated the change log a little

- skopt/learning/gaussian_process/tests/test_gpr.py
- skopt/learning/gaussian_process/tests/test_kernels.py
Refactors two more tests to use `pytest.mark.parametrize`
> Refactors tests

- .gitignore
- skopt/optimizer/optimizer.py
- skopt/tests/test_optimizer.py
This is an attempt to fix #351.
Let me know if that's the correct approach. I will be happy to add more unit tests accordingly.
> MRG: raises a ValueError whenever base_estimator is tree-based and acq_optimizer evaluates to False

- requirements.txt
Closing https://github.com/scikit-optimize/scikit-optimize/issues/377#issuecomment-303594182
> Remove cython from the requirements

- skopt/__init__.py
- skopt/tests/test_utils.py
- skopt/utils.py
> [MRG] add expected_minimum util

- skopt/optimizer/base.py
- skopt/optimizer/forest.py
- skopt/optimizer/gbrt.py
- skopt/optimizer/gp.py
- skopt/optimizer/optimizer.py
- skopt/tests/test_common.py
- skopt/tests/test_deprecation.py
- skopt/tests/test_optimizer.py
Fixes the bug I found in https://github.com/scikit-optimize/scikit-optimize/pull/343#issuecomment-304805380
Seems like we only fit a model if you call `tell` after exhausting the random points, not if you call it in between and then never again.
> [MRG] Add test to check we fit a model when a point is provided

- examples/ask-and-tell.ipynb
Tidy up that left over line in the ask and tell notebook
> [MRG] Tidy up the ask and tell notebook

- skopt/learning/gaussian_process/kernels.py
- skopt/learning/gaussian_process/tests/test_gpr.py
- skopt/learning/gaussian_process/tests/test_kernels.py
- skopt/learning/tests/test_gbrt.py
- skopt/optimizer/forest.py
- skopt/optimizer/gbrt.py
- skopt/optimizer/gp.py
- skopt/optimizer/optimizer.py
- skopt/plots.py
- skopt/searchcv.py
- skopt/space/space.py
- skopt/tests/test_gp_opt.py
- skopt/tests/test_optimizer.py
- skopt/tests/test_searchcv.py
- skopt/tests/test_utils.py
- skopt/utils.py
Should change anything or add new features ... just reduce the number of complaints from the linter.
> [MRG] PEP8 all the things

- setup.py
- skopt/__init__.py
Fixes #308. I went with 0.4 because that's the highest version in the change log.
> [MRG+1] update version to 0.4

- .gitignore
- skopt/optimizer/optimizer.py
- skopt/utils.py
Fixes #420  to make parameter case insensitive.
> [MRG] Quick fixup

- MANIFEST.in
Hey-lo,
I'm [building a version](https://github.com/conda-forge/staged-recipes/pull/3351) of `scikit-optimize` using [`conda`](http://conda.pydata.org/) for [conda-forge](http://conda-forge.github.io/). When possible, we try to include a link to the license file in the `meta.yaml` specification for the build; doing so requires the license be indexed in an explicit [`MANIFEST.in`](https://docs.python.org/2/distutils/sourcedist.html#manifest-related-options) file so that it gets included in the source distribution. This pull adds a `MANIFEST.in` that will bundle the license, other `.md` files, and other `.rst` files with the source distribution.
> [MRG] Create MANIFEST.in

- skopt/tests/test_common.py
- skopt/tests/test_dummy_opt.py
- skopt/tests/test_forest_opt.py
- skopt/tests/test_gp_opt.py
Fixes #449 
Trying to cut down on the combinatorics mostly.
> [MRG] Shaving off some seconds from the tests

- skopt/space/space.py
We were documenting the order of the arguments in the wrong order ...
> [MRG] Fix space documentation

- README.rst
- skopt/tests/test_utils.py
- skopt/utils.py
> [MRG] Add ask-n-tell example to README

- skopt/learning/gaussian_process/gpr.py
> FIX: avoid deprecation warnings of y_train_mean

- README.rst
Fixes the double CircleCI badge issue in our README.
> [MRG] Fix Travis badge

- skopt/searchcv.py
Fixes #466 
Move ._fit method inside the BayesSearchCV - maybe a temporary solution. Lets see if this breaks on Travis still.
> [MRG] fix BayesSearchCV on sklearn 0.19

- skopt/searchcv.py
- skopt/tests/test_searchcv.py
> [MRG] Fix the space enumeration of the BayesSearch, add corresponding test

- README.rst
- setup.py
- skopt/__init__.py
Preparation for releasing v0.4. Once this get's merge I'll tag the new version and we should have a new release.
What about #465? I think the test I added should pass? Should we wait for that PR?
> Bump version to 0.4

- skopt/space/transformers.py
As discussed in issue #503 this should be ready to merge
> Fix issue #503

- skopt/plots.py
This was for issue [490](https://github.com/scikit-optimize/scikit-optimize/issues/490) about figure sizes
> Size argument added to control the size of facets in objective plotting

- skopt/space/space.py
- skopt/tests/test_space.py
> Check bounds for Dimensions subclasses

- README.rst
`+` makes definitely for a prettier function, and it's in line with the toy example in the Intro.
> Fixed example in readme.

- skopt/optimizer/base.py
- skopt/optimizer/dummy.py
- skopt/optimizer/forest.py
- skopt/optimizer/gbrt.py
- skopt/optimizer/gp.py
- skopt/optimizer/optimizer.py
This is to solve issue #[519](https://github.com/scikit-optimize/scikit-optimize/issues/519).
> Fix docstring inconsistency of bounds in optimizers

- skopt/space/space.py
- skopt/tests/test_space.py
> Add property name to Dimension

- skopt/optimizer/base.py
- skopt/optimizer/forest.py
- skopt/optimizer/gp.py
- skopt/optimizer/optimizer.py
- skopt/space/transformers.py
- skopt/tests/test_common.py
- skopt/tests/test_forest_opt.py
- skopt/tests/test_gp_opt.py
- skopt/tests/test_optimizer.py
- skopt/tests/test_utils.py
- skopt/utils.py
Fixes #499 
Pass an integer derived from the random state to our regressors instead
of sharing the random state with them.
> [MRG+1] Fix random seed of regressors

- README.rst
What do you think about this?
Can/should we list NYU and Saarland University?
> [MRG] Add "made possible by" section to README

- skopt/searchcv.py
> Doc: remove surrogate, add optimizer_kwargs to BayesSearchCV docstring.

- .pep8speaks.yml
Experimenting with pep8 speaks and the config for it.
> [MRG] Experimenting with pep8speaks

- skopt/learning/gaussian_process/gpr.py
- skopt/tests/test_gpr.py
See https://github.com/scikit-optimize/scikit-optimize/issues/559
> [MRG+1] Modified gpr so that kernel uses noise

- README.rst
- postBuild
The `postBuild` script get's executed at the end and install `skopt`.
> [MRG] Add link to mybinder.org

- CHANGELOG.md
- skopt/tests/test_space.py
Include recently merged changes in the changelog. Anything else to add?
> [MRG] Update the CHANGELOG

- skopt/space/space.py
- skopt/tests/test_space.py
> [MRG] Fix __repr__ for Categorical dimensions with many options

- CONDUCT.md
- CONTRIBUTING.md
I wanted to refer to our code of conduct and noticed that we do not have one. This surprised me as it is something that is fairly standard for a community to have. While there has not been a need for a formal document until now, stating what we already practice in plain sight is good practice. This signals to others what we stand for, what behaviour is encouraged, what behaviour is not tolerated, and how to resolve differences.
There are two gaps in the current proposal: the names of two people who are external to the project that can serve as contacts independent of the maintainers of scikit-optimize. I have two people in mind who I have contacted. If you have ideas/proposals please ask them first before posting their names here. Ideas are welcome.
Please take a moment to read the COC, …
> [MRG+1] Add a code of conduct

- requirements.txt
- setup.py
Related to release of v0.5
#578
> [MRG] Bump version numbers and dependency on sklearn

- README.rst
> Add Zenodo DOI badge!

- README.rst
- skopt/__init__.py
This got forgotten for the release candidate.
See #578
> [MRG] Bump version tags

- skopt/searchcv.py
- skopt/tests/test_searchcv.py
This was easier than I thought. Implement issue #623
> [MRG+1] separate n_points from n_jobs

- skopt/space/space.py
- skopt/tests/test_space.py
> [MRG+2] Dimensions supporting boolean np.array

- build_tools/circle/install.sh
- build_tools/travis/install.sh
- setup.py
- skopt/__init__.py
- skopt/plots.py
Fixes #637 
I am not sure what I think of this. On the one hand it feels like it is the user's problem if they can't setup `matplotlib` properly, on the other hand there are plenty of use-cases for skopt without plotting.
Generally we should try and find out how other libraries deal with this.
> [MRG+1] Deal with matplotlib being broken on some OSX systems.

- skopt/optimizer/base.py
- skopt/optimizer/optimizer.py
The initialization of the optimizer class has a function `_check_argument`. I don't know if this has other usage to be separated. So I try to refactor the argument configuration process.
I also edited some comments in base file to improve the readability.
> [MRG+1] Refactor initialization of Optimizer and improve readability of comments of base optimizer

- .gitignore
- requirements.txt
- setup.py
- skopt/space/space.py
- skopt/tests/test_space.py
Per discussion in #651 
added classmethod in Space.from_yaml() to allow for external file to define Space parameters
added unittest in test_space.py
> [MRG+1] Adding ability to define Space parameters via yaml file

- skopt/searchcv.py
> Include fit_params in BayesSearchCV refit

- skopt/searchcv.py
- skopt/tests/test_searchcv.py
> Use native python types inside BayesSearchCV

- skopt/acquisition.py
This PR fixes the numpy broadcasting issues in `acquisition.gaussian_ei` and `acquisition.gaussian_pi` described in #726.
> Fix numpy broadcasting issues in gaussian_ei, gaussian_pi

- CHANGELOG.md
- README.rst
- skopt/__init__.py
Followed instructions in the `README.rst`.
> Bump version numbers for new release

- skopt/space/space.py
- skopt/space/transformers.py
- skopt/tests/test_space.py
After a few requests and confusions about this, there didn't seem to be any reason to not implement it. Referring to issues #735 and #712 . This is my first PR to this library, so while I'm happy to contribute I also wish to respect the current code and will make changes/take suggestions happily!
> [MRG] Add log-uniform prior to Integer space

- README.rst
- skopt/plots.py
- skopt/tests/test_plots.py
Evaluate and merge PR #675 with upstream
> [MRG] PR #675

- skopt/searchcv.py
- skopt/tests/test_searchcv.py
> [MRG] Fix searchcv rank 

- doc/conf.py
- doc/whats_new/v0.7.2.rst
- skopt/__init__.py
> [MRG] Fix version and release string in doc

- README.rst
Found this broken link while looking at the library. Wanted to quickly fix it :).
> Updated broken link to introduction of bayesian optimization example

- examples/plots/visualizing-results.py
- examples/strategy-comparison.py
cmap of branin plot has the same colormap as the objective plot
> Fix issue #624

- doc/whats_new/v0.8.rst
- skopt/space/transformers.py
- skopt/tests/test_optimizer.py
- skopt/utils.py
* This fixes issue #589
* Normalize works also when low==high
* normalize_dimensions uses normalize transform also for categorical
> Fix full categorical spaces on Gaussian process based regressors

- examples/ask-and-tell.py
> Use GP as base estimator in the ask and tell example

- doc/modules/classes.rst
- examples/plots/partial-dependence-plot-2D.py
- examples/plots/partial-dependence-plot-with-categorical.py
- examples/plots/partial-dependence-plot.py
- skopt/plots.py
- skopt/space/space.py
- skopt/tests/test_plots.py
- skopt/tests/test_space.py
- skopt/utils.py
Evaluation of PR #579 
Fixes issues:
* #182
* #388
* #576
* #648
* #740
> [MRG] Eval pr #579 - Rewrote parts of plotting functions and add two new plotting functions

- doc/whats_new/v0.8.rst
- skopt/space/space.py
- skopt/space/transformers.py
- skopt/tests/test_space.py
- skopt/tests/test_transformers.py
* Use _transpose_list_array helper function in space to reduce code
* Use eps value also in inverse_transform in Normalize
* Clip inverse_transform also for Integer
* Tries to fix issue #877
> Try to fix issue with Integer out of bounds in transform

- skopt/optimizer/gp.py
I fixed one small spelling mistake.
Thank you for making this project!
> Fix small spelling mistake

- doc/templates/index.html
- doc/whats_new.rst
- doc/whats_new/v0.8.rst
- doc/whats_new/v0.9.rst
- skopt/learning/gaussian_process/gpr.py
- skopt/tests/test_acquisition.py
Fixes changed introduced by https://github.com/scikit-learn/scikit-learn/pull/15782/files
> [MRG] Fixes GaussianProcessRegressor for sklearn >= 0.23

- skopt/utils.py
> [MRG] Keep prior when normalizing Integer spaces.

- skopt/space/transformers.py
> [MRG] Correct documented default is_int for Normalize.

- skopt/utils.py
Reverts scikit-optimize/scikit-optimize#1021
> Revert "[MRG] Keep prior when normalizing Integer spaces."

- skopt/space/space.py
> [MRG] Check whether prior values are valid.

- .circleci/config.yml
> [MRG] update packges in circleci deps

- .circleci/config.yml
- doc/whats_new/v0.9.rst
- examples/sklearn-gridsearchcv-replacement.py
- skopt/learning/gaussian_process/gpr.py
- skopt/searchcv.py
- skopt/tests/test_plots.py
- skopt/tests/test_searchcv.py
This PR fix compatibility with scikit-learn 1.0:
- Fixes #1061
- Fix tests using outdated scikit-learn API to load datasets
> [MRG] Fix GaussianProcessRegressor for scikit-learn 1.0
