scikit-optimize/scikit-optimize

- CONTRIBUTING.md
Added a inimal contribution guide in `CONTRIBUTING.md`. It lacks some details
on the mechanics of actually contributing.
NB. we should pick a license
> No contribution guidelines

- examples/plot_1d_demo.py
- skopt/__init__.py
- skopt/gp_opt.py
A minor pull request to make `_acquistion_func` public. Also renamed it as `gp_acquisition_func` since the actual acquisition function depends on the distribution of the posterior
> Make gp_acquisition_func public

- skopt/gbt.py
- skopt/tests/test_gbt.py
Started a simple wrapper for regressors like GBTRegressor to provide uncertainty estatimates as well
as central predictions.
Any ideas on how to test that this indeed gives the central and 68% confidence interval (right terminology??) predictions? Best idea so far is to use a very large number of samples on a simple problem and check that the predicted standard deviation is approximately equal to the std used when sampling.
Todo:
> [WIP] GBTRegressor does not provide uncertainty estimates

- skopt/benchmarks.py
- skopt/tests/test_benchmarks.py
- skopt/tests/test_gp_opt.py
Refactored benchmark functions into their own module and added
some basic (in)sanity tests for each.
> Benchmark functions were locked into one of the tests

- skopt/acquisition.py
- skopt/gbrt_opt.py
- skopt/gp_opt.py
- skopt/learning/gbrt.py
- skopt/tests/test_acquisition.py
- skopt/tests/test_gbrt.py
- skopt/tests/test_gbrt_opt.py
- skopt/tests/test_gp_opt.py
Allow `return_std` parameter for GBRT.predict
Move `_ei_improvement` and `acquisition` into `gaussian_acquisition` which suggests that the conditional is a gaussian.
> Refactor _ei_improvement into gaussian_acquisition

- skopt/acquisition.py
- skopt/gbrt_opt.py
- skopt/gp_opt.py
- skopt/tests/test_acquisition.py
- skopt/tests/test_gbrt.py
- skopt/tests/test_gbrt_opt.py
- skopt/tests/test_gp_opt.py
Down to to one complaint about a long line in `skopt/__init__.py` don't think
there is much we can do about that if we want to have the badge.
For future use I used `flake8 skopt/*`.
> Applying the flake8 steamroller

- skopt/tests/test_dummy_opt.py
- skopt/tests/test_gp_opt.py
Squashing some warnings. I added
```python
import traceback
import warnings
import sys
def warn_with_traceback(message, category, filename, lineno, file=None, line=None):
traceback.print_stack()
log = file if hasattr(file,'write') else sys.stderr
log.write(warnings.formatwarning(message, category, filename, lineno, line))
raise RuntimeError
warnings.showwarning = warn_with_traceback
```
to `skopt/__init__.py` and then ran `nosetest --pdb`. Is there a way to
get the same effect via env variable or commandline argument for nose?
> Squashing warnings

- skopt/learning/forest.py
- skopt/learning/tests/test_forest.py
- skopt/learning/tree.py
Described in section 4.3.2 of http://arxiv.org/pdf/1211.0906v2.pdf (`\sigma^2_min` = 0.01)
"To avoid making deterministic predictions for leaves with few data points, we round the stored variance up to `sigma^2_min`=0.01
> Round off variance in each tree to 0.01 in accordance with SMAC

- skopt/benchmarks.py
- skopt/tests/test_gp_opt.py
- skopt/tests/test_tree_opt.py
- skopt/tree_opt.py
This fixes #97, modulo the fact that the function to minimize actually returns a float.
The main issue was that `Xi = np.zeros((maxiter, space.n_dims))` was forcing entries to be cast to floats, no matter the type of the dimensions. Samples are now stored in a list instead, as was done in `gp_minimize`.
> [MRG] fix support for categorical variables

- .travis.yml
- skopt/space.py
- skopt/tests/test_space.py
Fixes https://github.com/scikit-optimize/scikit-optimize/issues/87
This was easier than I thought. Just a minor change.
```python
Categorical(1, 2, 3, 4)
```
becomes
```python
Categorical((1, 2, 3, 4))
```
This does not affect the public API of the `minimize` functions in any way except if the user explicitly provides a dimension as an instance of Categorical.
> [MRG] Python 2.7 Support

- skopt/benchmarks.py
- skopt/space.py
- skopt/tests/test_dummy_opt.py
- skopt/tests/test_space.py
This is a solution for #86. 
Points (in the original space) are now represented as a list of lists of values, where values are represented in their own original type, without coercion. This is the format expected by `space.transform` and returned by `space.inverse_transform` and `space.rvs`. Also, this means that functions to optimize are assumed to support as input a list of values. 
Points (in the transformed space) are represented as a Numpy array as before, since this is the most convenient for optimisation.
> [MRG] Space API: always use list of lists of values

- skopt/space.py
- skopt/tests/test_space.py
related to #142 
to be compatible with `Space.transformed_bounds`, Categorical.transformed_bounds` needs to output a single tuple when `transformed_size` is 1, instead of a list with 1 tuple.
> fix Categorical dimension transformed_bounds for len(categories) == 2

- skopt/plots.py
All changed are related to plotting.
Add `x` axis tick labels for plots on the diagonal
Add option to switch between `linear` and `log` scale for
contour plots.
Switching to log scale for `branin` revealed that we
also need to transpose the `zi` for the contour plots. After the fix
in #167 and seeing `branin` in log-scale it was obvious we needed to also transpose it.
Before:
After:
> x axis tick labels, log scale and zi.T

- skopt/gp_opt.py
- skopt/space.py
Clearly, lbfgs does not make sense for Integer and Categorical spaces since even though the acquisition function may be continuous, the actual function itself isn't. The lbfgs optimization procedure might lead to values in the transformed space in between 0 and 1, which might break inverse transform.
In this PR, search is set to lbfgs automatically only when all the dimensions are continuous.
> [MRG] Allow search=auto in gp_minimize

- skopt/gp_opt.py
- skopt/tests/test_common.py
- skopt/tests/test_tree_opt.py
- skopt/tree_opt.py
This fixes a bug that allows `n_random_starts` to be zero, when the initial points are provided.
In master:
```
space = [(-5.0, 10.0), (0.0, 15.0)]                                 
x0 = [[1, 2], [3, 4], [5, 6]]
n_calls = 10
gp_minimize(branin, space, x0=x0, y0=[1,2,3], n_random_starts=0, n_calls=10)
ValueError: Expected `n_random_starts` > 0, got 
```
> [MRG] [BUG] Allow n_random_starts=0, when x0 and y0 is provided

- skopt/tests/test_forest_opt.py
Fixes https://github.com/scikit-optimize/scikit-optimize/issues/127
The tricky test for passing was bench 2. On examining one of the random states, for that particular random state the initial points were in the region [-6, 5) and hence the RF was not able to be a good surrogate model for bench 2.
The fix was to warm start by pseudo sampling from [-6, 0] and [0, 6]
> [MRG] Check_minimize should pass all times instead of a majority

- .codecov.yml
- .travis.yml
- build_tools/travis/install.sh
This prints a list of the slowest tests and uploads the coverage (from py3.5) to codecov so we can actually look at it.
To see if we can speed up the tests we need to see what is slow, otherwise we will never think about it. As we already collect the coverage info it also makes sense to put it somewhere so we can see it -> we might start improving coverage.
> [MRG] Time tests and report coverage

- build_tools/circle/install.sh
- build_tools/travis/install.sh
This is a takeover from #228. After some digging I found ContinuumIO/anaconda-issues#1068. Seems like @continuumio broke something so waiting for them to fix it after which we should undo this pinning.
> [MRG] Pin PyQT to 4.11 temporarily

- examples/strategy-comparison.ipynb
- examples/visualizing-results.ipynb
- skopt/optimizer/forest.py
- skopt/tests/test_common.py
- skopt/tests/test_forest_opt.py
This is a fix for issue #153 to change the arguments to the base_estimator parameter of the forest_minimize function to uppercase.  I made edits in the forest.py and test_forest_opt.py files to reflect the changes.
This is my first contribution so I'm open to feedback on any mistakes I'm making.  (Blame @betatim and Linear Digressions for bringing me here :smile:)
> [MRG] Changing options for base_estimator to uppercase

- AUTHORS.md
- README.md
- build_tools/circle/execute.sh
- build_tools/circle/install.sh
- circle.yml
Mainly administrative stuff.
I split the CircleCI stuff because the length of the log file that you can see online is limited and mainly full of download bars for setting up the env which makes it hard to see what is actually failing. Hopefully this way we get better online logs.
> [MRG] Update AUTHORS, link roadmap and split circleci build

- skopt/learning/__init__.py
- skopt/learning/gpr.py
- skopt/learning/tests/test_gpr.py
- skopt/optimizer/gp.py
> [MRG] Add noise attribute to skopt.GaussianProcessRegressor

- build_tools/circle/execute.sh
Here is the circleci test with the updated fail fast execute.sh script:
https://circleci.com/gh/thomasjpfan/scikit-optimize/15
For testing purposes, I created a branch with the same script, but with a syntax error in bayesian-optimization.ipynb and ran it on circleci, https://circleci.com/gh/thomasjpfan/scikit-optimize/17, to show that the testing fails with the first error.
While updating the script, I noticed that if the notebook files don't have supporting files i.e. images, the `cp -r ${SKOPT_HOME}/examples/*_files ${HOME}/doc/skopt/notebooks` will fail. So I have updated that line with a find command. To make sure it works, I ran a circleci test where the example notebooks don't have supporting files:
https://circleci.com/gh/thomasjpfan/scikit-optimize/16
> [MRG+1] Fail fast for examples

- .gitattributes
I'm sorry, this PR is _really_ nitpicking.
Currently, the language bar shows that `skopt` has 15.8% Mako and 2% Shell, although these are only for the build tools.
Wouldn't it be better to exclude them and indicate that `skopt` is 100% Python?
We could also include the Jupyter notebooks in the `examples` folder.
> Ignore build_tools for the language bar

- examples/store-and-load-results.ipynb
- skopt/__init__.py
- skopt/tests/test_utils.py
- skopt/utils.py
See #190 
To do:
~~Be more specific when catching the pickling exception, search for `func` in the error message~~
> Persistence with skopt.dump() and skopt.load()

- benchmarks/bench_branin.py
- benchmarks/bench_hart6.py
- skopt/tests/test_acquisition.py
- skopt/tests/test_dummy_opt.py
- skopt/tests/test_forest_opt.py
- skopt/tests/test_gp_opt.py
- skopt/tests/test_space.py
- skopt/tests/test_utils.py
This PR removes tests on `branin` and `hart6`, that should rather be considered as benchmarks.
Fix for #242.
> [MRG] Remove tests on branin and hart6 

- skopt/optimizer/base.py
- skopt/optimizer/forest.py
- skopt/optimizer/gp.py
- skopt/space/space.py
- skopt/space/transformers.py
- skopt/tests/test_space.py
We should normalize integer dimensions as well because the isotropic GP hyper-parameters might be highly dominated by these if they are on a completely different scale from the others such as from [1, 47]
> [MRG+1] Normalize integer dimensions

- skopt/optimizer/base.py
I am continuously saving the current_result in gp_minimize() using a wrapper around dump() as a callback after every iteration like this:
```
def dump_cb(res):
res2 = copy.deepcopy(res)
del res2.specs['args']['func']
del res2.specs['args']['callback']
dump(res2, 'result.pkl', store_objective=True)
```
(I copied the deepcopy from https://github.com/scikit-optimize/scikit-optimize/blob/master/skopt/utils.py#L88 and added deletion of the callback as it was not serializable - it might make a useful additon to the callbacks.py module, let me know if you want me to implement it)
I then want to be able to inspect the ongoing training progress using the visualization plots. this worked fine except for plot_objective() which crashed because the result was missing the models in the following line: …
> include models in result passed to callback(s)

- circle.yml
Fixed a typo in the circleci config to have a PR to play with to test out circleci integration.
Currently it only builds merges, but not on each PR. I  enabled "Build forked pull requests" (which was off). I expect we get builds for PRs now. Don't see a way to enable it via the config file though :-/
> [WIP] Investigate CircleCI status

- .travis.yml
Let's see how we do on the next version of python
> Enable python 3.6 on travis

- skopt/optimizer/gbrt.py
Fixes #326 
What would be a good way to test for output when the verbose flag is set in a test (without having to resort to replacing `sys.stdout` myself)?
> [WIP] Fix passing on the verbose flag in GBRT

- skopt/optimizer/base.py
- skopt/tests/test_common.py
The test I added would have failed before. The entries in `res.x_iters` had different dimensions for a 1D problem.
> [MRG] Add test for two vs one dimensional problems with initial points

- setup.cfg
Counting our tests when we compute the coverage feels like cheating 😀
> Remove tests from computation of coverage

- skopt/optimizer/optimizer.py
This follows the same reasoning of #363.
FYI:  ``np.allclose(x, 0.)`` is equivalent to  ``abs(x) <= 1e-8``, but the latter is faster whenever ``x`` is a scalar.
> [MRG+1] ENH: improve performance of ask method in Optimizer

- skopt/space/space.py
This change is based on the fact that:
```
In [2]: %timeit np.abs(1 - 2)
The slowest run took 166.84 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 953 ns per loop
In [3]: %timeit abs(1 - 2)
The slowest run took 23.36 times longer than the fastest. This could mean that an intermediate result is being cached.
10000000 loops, best of 3: 80.9 ns per loop
```
> [MRG+1] ENH: improve performance of distance methods in Dimension subclasses

- .gitignore
- .travis.yml
- README.md
- build_tools/circle/install.sh
- build_tools/travis/install.sh
- skopt/__init__.py
- skopt/learning/gaussian_process/tests/test_kernels.py
- skopt/learning/tests/test_forest.py
- skopt/tests/test_common.py
- skopt/tests/test_dummy_opt.py
- skopt/tests/test_forest_opt.py
- skopt/tests/test_gp_opt.py
- skopt/tests/test_space.py
Converts tests from nosetests to pytest. The only real change needed was to convert the yield statements that nosetests uses to function calls. pytest shows the duration of test runs by default. nose is still a test requirement because of `assert_array_equal` from the sklearn library.
#220
> [MRG+1] Converts tests to pytest

- skopt/optimizer/forest.py
As described in #367, ``acq_optimizer`` is not documented in ``forest_minimize`` and its value does not have any effect on ``forest_minimize``.
In this PR, I propose removing ``acq_optimizer`` from  ``forest_minimize``. As mention by @betatim, one caveat arises when another option (besides ``'sampling'``) for ``acq_optimizer`` is implemented. That can be solved by adding ``acq_optimizer`` back to the list of arguments and proper docstrings.
Fixes #367.
> [MRG+1]: Remove acq_optimizer from forest_minimize

- skopt/optimizer/optimizer.py
- skopt/space/space.py
- skopt/tests/test_common.py
- skopt/tests/test_space.py
Fixes #371 
Create a new Space instance from an existing one. The goal of this PR is to allow people to pass a `Space` instance everywhere we accept a list of dimensions as argument.
> [MRG] Add 'copy constructor' to Space

- examples/bayesian-optimization.ipynb
Typo, "f of may be noisy"  → "of f may be noisy" in https://scikit-optimize.github.io/notebooks/bayesian-optimization.html
> Typo, "f of may be noisy"  → "of f may be noisy"

- README.rst
- skopt/learning/gaussian_process/tests/test_gpr.py
- skopt/learning/gaussian_process/tests/test_kernels.py
- skopt/learning/tests/test_gbrt.py
- skopt/tests/test_acquisition.py
- skopt/tests/test_benchmarks.py
- skopt/tests/test_callbacks.py
- skopt/tests/test_common.py
- skopt/tests/test_dummy_opt.py
- skopt/tests/test_forest_opt.py
- skopt/tests/test_gp_opt.py
- skopt/tests/test_optimizer.py
- skopt/tests/test_space.py
- skopt/tests/test_utils.py
This PR implements changes proposed in #293 by adding pytest attributes to all tests depending on their run time.
I picked the threshold between slow and fasts tests to be at 1 second. This yields all fast tests to run in approx 10s while the slow tests take another 10min. If one test is performed multiple times with different input parameters, only the slowest run is taken into account.
* To only run the fast tests: `pytest -m 'fast_test'`
* To only run the slow tests: `pytest -m 'slow_test'`
* To only run tests w/o any attribute: `pytest -m 'not slow_test and not fast_test'`
> Implements pytest attributes to select fast and slow running tests

- README.rst
- build_tools/circle/execute.sh
- build_tools/circle/install.sh
- build_tools/travis/install.sh
Closes #404 and adds a (temporary?) workaround to the install instructions.
We need to install numpy before trying to install scikit-optimize
as numpy is needed to run the `setup.py` of scikit-garden which
we depend on. While scikit-garden declares numpy as a dependency the seutp.py can't be executed without it being installed, which creates some kind of infinite loop.
The discussion of having numpy in `setup.py` is in scikit-garden/scikit-garden#23
> [MRG] Fix install instructions to explicitly install numpy

- examples/ask-and-tell.ipynb
- skopt/optimizer/forest.py
- skopt/optimizer/gbrt.py
- skopt/optimizer/gp.py
- skopt/optimizer/optimizer.py
- skopt/tests/test_gp_opt.py
- skopt/tests/test_optimizer.py
- skopt/utils.py
1. Allow base_estimator to be one of "gp", "et", "rf" or "gbrt", by default "gp"
2. Add a function `cook_skopt_estimator` in utils that allows to cook the default skopt estimators.
> [MRG] Allow base_estimators to be strings

- CHANGELOG.md
BayesSearchCV was missing, as are others (I am sure).
Let's try and get the log updated. If you know something that should be mentioned help me out by posting here. Will wait a bit and then merge this PR.
(We should get better at keeping it up to date as part of merging PRs.)
> [WIP] Update the changelog

- CHANGELOG.md
- skopt/learning/gbrt.py
- skopt/learning/tests/test_gbrt.py
- skopt/optimizer/dummy.py
- skopt/optimizer/optimizer.py
- skopt/tests/test_common.py
- skopt/tests/test_optimizer.py
- skopt/tests/test_utils.py
- skopt/utils.py
Fixes #406 
This removes the need to special case dummy_minimize by adding
the ability to switch to supplying only random suggestions in
the Optimizer class.
Still uses `None`, needs changing to "dummy".
> [MRG] Add support for random "base estimator" in Optimizer

- .travis.yml
- skopt/optimizer/gp.py
- skopt/optimizer/optimizer.py
- skopt/utils.py
This is a small step towards obtaining the same results with `gp_minimize` and the `Optimizer` class noted in https://github.com/scikit-optimize/scikit-optimize/issues/402. 
The code extracts the code responsible for transforming the `dimensions` in `gp_minimize`, creating a new function, ~~`transform_gpdims`~~  ~~`transform_dims`~~ `normalize_dimensions`, which can then be used by both `gp_minimize` and `Optimizer`.
> [MRG+1] Refactoring dimension transformations in `gp_minimize` to be used by `Optimizer`.

- skopt/__init__.py
- skopt/optimizer/base.py
- skopt/optimizer/dummy.py
- skopt/optimizer/optimizer.py
- skopt/tests/test_utils.py
- skopt/utils.py
Fix bug in `has_gradients` and add tests for it at the same time.
`has_gradients` was returning `not has_gradients` as far as I could tell.
One thing I'd like to double check, the special case for `space.is_categorical` when constructing the GP kernel: Hamming kernels are only for spaces which have exclusively categorical dimensions. Is that correct?
> [MRG] Fix bug in has_gradients

- skopt/callbacks.py
- skopt/tests/test_callbacks.py
Creates a new `DeadlineCallback` class, an early stopping callback for fixed time budgets. When running optimizations on our clusters, we have fixed wall times for the jobs to be completed within. After pushing the clock a couple of times, I decided to write this class. 
After specifying the total amount of time you would like the optimization to run, the callback keeps track of the time taken for each iteration (exactly as in `TimerCallback`). It then decrements the iteration time from the total time, saving this as `time_remaining`. The early stopping occurs when the `time_remaining` is less than or equal to longest single iteration time. 
> Note: This code has some repetition from the `TimerCallback`. I originally tried to use multiple inheritance with both the `TimerCallback` and the …
> [MRG+1] DeadlineCallback, early stopping for a fixed budget

- skopt/acquisition.py
- skopt/tests/test_acquisition.py
This acquisition function aims at reducing the overall uncertainty of our objective function approximation.
This is useful if you want to accurately gauge the effect of every hyperparameter on the objective function, typically to set proper ranges for the subsequent optimization or to remove a parameter completely.
The `gaussian_a_opt` function uses the standard deviation provided by the base estimator and samples those points first where it is maximal.
Suggestions for improvement are welcome.
> [MRG+1] Implement greedy A-optimal acquisition function for pure exploration

- skopt/optimizer/optimizer.py
- skopt/tests/test_common.py
When using LBFGS as minimizer for the acquisition function we do not
need to sample as many points as when we optimise by random sampling.
This saves CPU time.
This illustrates https://github.com/scikit-optimize/scikit-optimize/issues/413#issuecomment-318578862
> [MRG] Reduce number of points sampled when using LBFGS

- skopt/tests/test_utils.py
Need to seek at the beginning of the file before loading the pickle
from the file.
This is probably a change in the joblib we bundle with scikit-learn between scikit-learn 0.18 and scikit-learn master.
Note that I think this is fine and has the same behaviour as pickle:
```py
import tempfile
import pickle
with tempfile.TemporaryFile() as f:
pickle.dump(object(), f)
pickle.load(f)
```
```
---------------------------------------------------------------------------
EOFError                                  Traceback (most recent call last)
<ipython-input-3-5857a6e21a79> in <module>()
4 with tempfile.TemporaryFile() as f:
5     pickle.dump(object(), f)
----> 6     pickle.load(f)
7 
EOFError: Ran out of input
```
Fixes part of #461.
> Fix test_utils.py with scikit-learn master

- skopt/space/space.py
- skopt/tests/test_space.py
Fixes #454 
Makes `Space(([False, True]))` produce a `Categorical` dimension instead of a `Integer`.
> [MRG+1] Fix handling of bool in Categorical space

- skopt/optimizer/gp.py
- skopt/optimizer/optimizer.py
- skopt/space/space.py
- skopt/tests/test_optimizer.py
- skopt/tests/test_utils.py
- skopt/utils.py
Follow up for #402 
This PR adds a test that checks if indeed `Optimizer()` and `gp_minimize()` give the same results when used with default settings.
For that to be true I had to modify `gp_minimize` to use the normalised space. @MechCoder should take a look to double check.
Thoughts on the points only being within 1e-5 of each other instead of being identical? The random points are exactly identical but then it seems thigns diverge a bit once we start using the GP :-/
> [MRG+1] Optimizer() and gp_minimize should be equivalent

- skopt/searchcv.py
The cloning function `sklearn.base.clone` fails with `BayesSearchCV` on master skopt. This PR contains fix.
> [MRG] Fix cloning of BayesSearchCV

- skopt/tests/test_optimizer.py
- skopt/utils.py
Fixes #487 
Added check for dimension of point and space.
Check is added in utils.check_x_in_space(), could also be added in __contains__ function of space, but then Exception message in check_x_in_space should be adapted.
> Check point dimension on tell

- skopt/plots.py
- skopt/space/space.py
See discussion history in #518 and #517.
I rebased to upstream/master and updated the code according to your suggestions.  (sorry for starting yet another pull request.  I always get entangled in git issues when trying to rebase.)
@glouppe :  Of what would you like me to generate screenshots?
Regarding `space.Categorical`, We could construct plottable dimensions along these lines:
`dims_to_plot = [not isinstance(dim, Categorical) for dim in space.dimensions]`, and go from there.  I think the property that we're missing is something like a `Dimensions.has_ordering`.  What do you think?
Updated use example:
```
import matplotlib.pyplot as plt
from skopt import forest_minimize
from skopt.plots import plot_evaluations, plot_objective
from skopt.benchmarks import branin as branin
bounds = [ …
```
> [MRG] Beautifying plots: dim-labels, log-scale.

- setup.py
as discussed in issue #530
Added the requirement in `setup.py`, left `requirements.txt` unchanged.
> added requirement for scipy >= 0.14.0 

- examples/parallel-optimization.ipynb
- skopt/learning/gaussian_process/gpr.py
- skopt/learning/gaussian_process/tests/test_gpr.py
- skopt/optimizer/optimizer.py
- skopt/tests/test_parallel_cl.py
- skopt/utils.py
This does two things: tries to fix the Circlie CI error we keep seeing about "not pos def matrix" in the parallel evaluation example and makes the calls with a parallel strategy reproducible by fixing the seed.
> [MRG] Fix not positive definitive matrix in parallel optimisation

- skopt/optimizer/gp.py
- skopt/tests/test_gp_opt.py
I think that gp_minimize should use the given optimizer, if it exists
> [MRG] gp_minimize should not use default estimator when a custom one is provided

- skopt/optimizer/gp.py
It seems that the actual default of ``acq_func`` is ``gp_hedge``, not ``EI`` as stated in the docstring.
> [DOC]: fix actual acq_func default value

- examples/sklearn-gridsearchcv-replacement.ipynb
- skopt/searchcv.py
- skopt/tests/test_searchcv.py
Doing *anything* in the `__init__` method of a sklearn estimator will most of the time break his compatibility with sklearn's clone, get_params and set_params, or the ability to fit it several times. It is in fact the case here, it would break if used in a Pipeline or other meta-objects in sklearn.
This PR is a quick (for now, dirty) proposal to fix the compatibility issues.
I've basically moved every lines of code that are not `self.foo = foo`, where foo is an arg, inside the fit() and add_space() methods.
Fixes #550 #551
> [MRG+1] Fix compatibility with sklearn

- skopt/optimizer/optimizer.py
- skopt/tests/test_optimizer.py
- skopt/tests/test_parallel_cl.py
The previous version used to create copies of the optimizer, which looked like this:
```
MultiOutputRegressor(estimator=MultiOutputRegressor(estimator=GaussianProcessRegressor(alpha=1e-10, copy_X_train=True,
kernel=1**2 * Matern(length_scale=1, nu=2.5),
n_restarts_optimizer=2, noise='gaussian', normalize_y=True,
optimizer='fmin_l_bfgs_b', random_state=2061968400),
n_jobs=1),
n_jobs=1)
```
The estimator inside `MultiOutputRegressor` is again a `MultiOutputRegressor`, which is automatically added for acquisition functions that incorporate time (EIps, PIps).
Basically, each call to copy() would wrap another `MultiOutputRegressor` around the base_estimator.
This affects at least #560.
> [MRG] Prevent the base_estimator from being wrapped multiple times

- skopt/space/space.py
- skopt/tests/test_space.py
Fixes #586 fixes #470 
Round tripping values using the log10 transform for a Real dimension
can lead to a value that was within the bounds of the space being
outside of the bounds. We now force values to be within bounds by
clipping the return value of inverse_transform() to (low, high).
> [MRG] Add clipping of inverse_transform values

- CHANGELOG.md
- examples/sklearn-gridsearchcv-replacement.ipynb
- skopt/searchcv.py
- skopt/space/space.py
- skopt/tests/test_searchcv.py
- skopt/tests/test_space.py
A continuation of #515 (seemed a bit easier to start a new PR). 
Additions in this PR:
* A new shiny iteration callback to BayesSearchCV!
* Dimensions can be defined by single element list / tuple, which is considered to be a dimension of Category type and fixes dimension value.
Tests / examples included.
> [MRG] Add iteration callback to BayesSearchCV, fixed value dimension

- skopt/optimizer/base.py
- skopt/optimizer/dummy.py
- skopt/optimizer/forest.py
- skopt/optimizer/gbrt.py
- skopt/optimizer/gp.py
- skopt/space/space.py
- skopt/tests/test_utils.py
- skopt/utils.py
This is a much improved version of PR #590 which was also discussed in various issues including #570 and #583.
It might be a good idea if I update the doc-strings of all optimizers to briefly describe that `func` can be wrapped using this decorator so as to use named arguments. Do you agree?
Thanks to @betatim for suggesting the use of a decorator which made this version very elegant.
I have not worked very much with decorators and this is a fairly advanced usage scenario, so I think it is better to direct the interested user to do an internet search if they want an explanation on how advanced decorators work in Python. See my comments in the code.
However, I do hope you appreciate the otherwise detailed level of commenting I have added, which is what I have been discussing in my other …
> [MRG+1] Added support for named arguments with objective function (NEW version)

- README.rst
- setup.py
This is my first pull request to you and my first contribution to anything open source where I don't know the owners personally. It's mostly to familiarize myself with the fact I have to fork the repo and push to a branch I own (because permissions) and other minutiae, but it also solves #569 by letting potential users know they can't use scikit-learn 0.18.0. Hopefully more substantial changes to come, since I've opened several issues I don't expect anyone else will fix for me.
> setup.py now reflects that skopt needs sklearn that has MaskedArray in its fixes.py

- skopt/benchmarks.py
- skopt/optimizer/optimizer.py
- skopt/tests/test_optimizer.py
I just noticed the optimizer's `copy()` method tampers with the objective values `yi`. Only affects acquisition functions with computation time.
This is required for #574.
Short explanation:
* The values in `yi` are in this case tuples of `objective_value` and `time`
* Each copy would again apply the logarithm on the time values
> [MRG+1] Fix copy for ask and tell with computation time

- CONTRIBUTING.md
This PR adds two sentences I kept repeating in PRs by newcomers (use of WIP and MRG) and tries to add a paragraph outlining other ways of contributing to the code base. We are good at adding code, reviewing code, and all things code but not so good at all of the other things. Do you think this paragraph will encourage people who add to our skill set to start contributing?
> [MRG] Extend contributing guidelines to encourage non code contributions

- skopt/searchcv.py
Computing the train score on each split during hyper-parameter search can be a significant overhead, and is not used by the algorithm for model selection, hence it's only useful for occasional exploration purposes. Most of the time it's not really useful.
Sklearn is already planning to set the default to `False`, see the documentation for `return_train_score`: http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html
This PR implement the change for BayesSearchCV.
> return_train_score default to False

- skopt/optimizer/optimizer.py
- skopt/tests/test_parallel_cl.py
**Update:**
*Description:*
This PR aims to solve the issue discussed in #560. Basically, it should fix the ask and tell API for the cases, where an acquisiton function that incorporates time is used.
*Status:*
- ~~Adapt the comments~~ (--> separate task)
*Changes:*
- Most of the work has been done in #572 and #593 
- This issue changes the lying step so that it also generates a time value when lying.
- The time value is generated in a similar way as the lie for objective value. However, when no previous evaluations exist, then the maximum possible runtime time `log(float.max)` is used.
***
Current state:
* I provided (or rather extended) a test which demonstrates the failure
Problems:
* During the lying step the time values are not considered at all (correct me if i am wrong)
* Within the …
> [MRG] Ask and tell for runtime optimization

- README.rst
- setup.py
- skopt/__init__.py
Fixes #633 
This bumps the version tags to v0.5.1 so we can replace the files associated to the v0.5 release.
I also included a section in the README that has a checklist of the things that need doing to create a new release.
> [MRG+1] Adding release documentation and bumping the version tag

- skopt/tests/test_space.py
- skopt/utils.py
Fixes #615 
The original error comes because the creation of the message for the exception fails. The reason the exception was being raised in the first place was because we computed the number of dimensions for the `HammingKernel` incorrectly.
> [MRG+1] Fix handling of Categorical only spaces

- skopt/tests/test_utils.py
- skopt/utils.py
I noticed that the result object of `gp_minimize` contained dimension objects that didn't have their assigned names anymore ([example](https://gist.github.com/cschell/e70bb403d79e4e73250d90952e33d130)). This seemed to be caused by `utils.normalize_dimensions()`, which did not pass on the `name`.
> [MRG] Don't lose dimension name when using `normalize_dimensions`

- skopt/callbacks.py
- skopt/tests/test_callbacks.py
Adds a new callback that can be used to save a checkpoint after each iteration with `skopt.dump`.
> [MRG] add new callback `CheckpointSaver`

- examples/interruptible-optimization.ipynb
After adding the `CallbackSaver` callback in #665 I figured that a short example would be nice, so here it is. I followed the style of the [store-and-load-results](https://github.com/scikit-optimize/scikit-optimize/blob/master/examples/store-and-load-results.ipynb) example, so I hope the format is appropriate.
> [MRG] Add example notebook for checkpoint callback

- skopt/plots.py
This PR adds a function for plotting the cumulative regret.
The code is totally similar to plot_convergence, maintaining the same signature. The cumulative regret is defined as the sum of the obtained values minus the global optimum: at epoch `i` the Cumulative Regret will be: ``CR(i) = \sum_{n=0}^i (f(x_n) - optimum)`` (assuming we are minimizing).
Intuitively, it measures how much an optimizer is effective at picking good points.
The global optimum can be given via the `true_minimum` argument or, if missing, the minimum value in the results will be used.
As an example, the function can be used in the following way:
```
from skopt import dummy_minimize, gp_minimize
from skopt.benchmarks import branin
from skopt.plots import plot_regret
D=[[-5.0, 10.0], [0.0, 15.0]]
rd = …
```
> [MRG] Function for plotting the cumulative regret

- skopt/acquisition.py
- skopt/tests/test_acquisition.py
This PR adds a slightly more informational error message for the input checking in ``_gaussian_acquisition``.
> [MRG] Improve error message if input check fails in _gaussian_acquisition

- skopt/tests/test_acquisition.py
The unit test I wrote earlier had an indentation bug. This PR fixes it.
cc @betatim
> [MRG] Fix bad indentation in test_gaussian_acquisition_check_inputs

- skopt/learning/gaussian_process/tests/test_kernels.py
- skopt/tests/test_common.py
- skopt/tests/test_gp_opt.py
Simplifies tests by using multiple `pytest.mark.parametrize` decorators instead of using `product`.
> RFC: Uses multiple pytest.marks decorators

- benchmarks/README.md
The existing link to the list of functions for benchmarking was broken and the file no longer exists there. Updated with the now working link.
> [MRG] Updated Broken Link to List of Benchmark Functions

- .codecov.yml
- .coveragerc
This setups the codecov check so that it doesn't comment in a PR thread and passes unless a PR reduces coverage.
Also changes where we exclude files from the coverage accounting.
> [MRG] Configure coverage creation and checks

- skopt/searchcv.py
Closes #762 
This allows CI to pass on master again and allows other PRs to carry on with the review process (e.g. this one #776).
This is in my opinion a temporary fix to the problem. `sklearn` has deprecated `fit_params` in the class constructor in favor of passing keyword parameters to the fit methods. `scikit-optimize` should probably follow suit.  However that will require a chain of deprecation action.
If the maintainer agrees, I think there should be a separate issue for deprecating `fit_params` in `BayesSearchCV.__init__` and exposing `fit_params` in `BayesSearchCV.fit`.
> [MRG] Allow BayesSearchCV to work with sklearn 0.21

- README.rst
- benchmarks/bench_ml.py
- examples/parallel-optimization.ipynb
- setup.py
- skopt/learning/gbrt.py
- skopt/optimizer/optimizer.py
- skopt/searchcv.py
- skopt/space/space.py
- skopt/space/transformers.py
- skopt/tests/test_searchcv.py
- skopt/tests/test_utils.py
- skopt/utils.py
Fixing `DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.`
Should resolve [#774](https://github.com/scikit-optimize/scikit-optimize/issues/774)
> Use joblib instead of sklearn.externals.joblib

- .coveragerc
- README.rst
- pytest.ini
- skopt/callbacks.py
- skopt/optimizer/base.py
- skopt/searchcv.py
- skopt/space/space.py
- skopt/tests/test_acquisition.py
- skopt/tests/test_benchmarks.py
- skopt/tests/test_callbacks.py
- skopt/tests/test_common.py
- skopt/tests/test_dummy_opt.py
- skopt/tests/test_forest_opt.py
- skopt/tests/test_gp_opt.py
- skopt/tests/test_optimizer.py
- skopt/tests/test_searchcv.py
- skopt/tests/test_space.py
- skopt/tests/test_utils.py
* Using collections.abc instead of collections for import
* Using  yaml.safe_load instead of yaml.load
* Replacing sklearn.utils.testing functions by numpy testing functions
* Using assert for assert_greater, assert_less, assert_true, assert_false, assert_greater_equal and assert_less_equal
* Replacing assert_raise_message by pytest.raises
* Replacing assert_warns_message by pytest.warns and assert checks
* Using NamedTemporaryFile(delete=False) with manual delete to fix the Unit test on WIndows
* Replacing from sklearn.metrics.scorer import check_scoring by from sklearn.metrics import check_scoring
* Using pytest.ini to register fast_test and slow_test
> [MRG] Reduce the amount of  deprecation warnings in unit tests

- skopt/searchcv.py
This partially solves #566 
I've created a dictionary called optimizer_results_ that stores the optimizer results as value and the optimizer as key. This makes it work if the user specifies multiple optimizers.
> [MRG] Return optimizer results in BayesSearchCV

- skopt/acquisition.py
Description of `gaussian_lcb()` parameter `kappa` is the opposite of what is true. 
See, e.g., https://scikit-optimize.github.io/stable/auto_examples/exploration-vs-exploitation.html?highlight=kappa
> kappa is only used if acq_func is set to “LCB”. xi is used when acq_func is “EI” or “PI”. By default the acqusition function is set to “gp_hedge” which chooses the best of these three. Therefore I recommend not using gp_hedge when tweaking exploration/exploitation, but instead choosing “LCB”, “EI” or “PI.
> Fix docstring: kappa is only used for LCB acquisition function

- README.rst
- doc/development.rst
The links to the milestone pages in the README and doc/development are broken. Pointing to milestones will remove the need to keep them updated. Same goes for the version number in README.
> readme & docs: fix outdated version number and milestone links

- examples/bayesian-optimization.py
Current:
This PR should fix both expressions
> Fix maths display in bayesian_optimization doc

- skopt/plots.py
* Fix position of red minimum line when `plot_dims` is something other than the first N dimensions
* Fix `xlim` of line plots along the diagonal so that the minimum line lines up with the marker in the contour plots below it.
* Add `show_points` option to allow user to decide whether to see the evaluated points. When the number of points is large and the plots are not that big, one can barely see the surrogate function behind the points.
* Add `cmap` option to allow user to choose the color map for the contour plots. If accepted, this should probably be extended to other functions as well.
> [MRG] Add options to plot_objective

- skopt/callbacks.py
- skopt/tests/test_callbacks.py
Stop the optimization if the improvement over the last n iterations is below a threshold.
Similar to, but not quite the same as DeltaY stopper. For instance, if the the search has already found the true minimum, and the 2nd best is more than `delta` away, DeltaY will never kick in.
> [MRG]Add hollow iterations early stopper

- doc/whats_new/v0.4.rst
There is a small typo in doc/whats_new/v0.4.rst.
Should read `strategies` rather than `stategies`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, stategies -> strategies

- skopt/callbacks.py
- skopt/tests/test_callbacks.py
* add new callback to stop optimization if the func value is lower than a given (by the user) threshold
* fixes #999
* I've implemented and tested this feature in a private repo
> [MRG] add ThresholdStopper()

- skopt/learning/gaussian_process/kernels.py
- skopt/space/space.py
- skopt/space/transformers.py
This will fix some numpy depreciation errors that appear due to the usage of float.
```
`np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```
It's also fixing `skopt/learning/gaussian_process/kernels.py:319: DeprecationWarning: invalid escape sequence \s` - although i'm not 100% certain how this fix will come out at the docs.
Unfortunately, i'm uncertain how to build / verify this - as it doesn't seem to be documented.
I'm hoping that CI passes, as i found no way to get …
> Fix numpy Deprecation errors

- doc/whats_new/v0.9.rst
- skopt/searchcv.py
Fixes https://github.com/scikit-optimize/scikit-optimize/issues/978
Fixes https://github.com/scikit-optimize/scikit-optimize/issues/987
Fixes https://github.com/scikit-optimize/scikit-optimize/issues/927
Fixes https://github.com/scikit-optimize/scikit-optimize/issues/990
Fixes https://github.com/scikit-optimize/scikit-optimize/issues/981 via updated scikit-learn
Fixes https://github.com/scikit-optimize/scikit-optimize/issues/1006
Fixes https://github.com/scikit-optimize/scikit-optimize/issues/718
Closes https://github.com/scikit-optimize/scikit-optimize/pull/951
> Remove BayesSearchCV(iid=) parameter deprecated in sklearn 0.24

- skopt/searchcv.py
Re-add `BayesSearchCV.best_score_`, needed by _examples/sklearn-gridsearchcv-replacement.py_.
Removed in 9461bfecc12c8cab7ae18a55e44e1d258b3c09c9 (#988), which [broke CircleCI docs build](https://app.circleci.com/pipelines/github/scikit-optimize/scikit-optimize/515/workflows/73a6b7c7-d299-4940-9020-63d6587b7b17/jobs/2840), which for some reason wasn't caught in PR CI.
> Re-add `BayesSearchCV.best_score_` needed by some examples

- examples/sklearn-gridsearchcv-replacement.py
- skopt/searchcv.py
This reverts commit c53998816481d150ccc745ffd07d022fdb1fd25d (https://github.com/scikit-optimize/scikit-optimize/pull/1031).
Instead, the fix is not to rely on `BayesSearchCV.best_score_`
in callbacks (i.e. until `BaseSearchCV.fit` computes it).
@glouppe I think this is the simpler fix. :crossed_fingers:
> Revert "Re-add `BayesSearchCV.best_score_` needed by some examples"

- examples/hyperparameter-optimization.py
Just a minor grammar error that I noticed in the docs. "Fewer" is used with countable things (like evaluations) while "less" is used with amounts (like time).
Thanks for a great library!
> [MRG] Fixed grammatical error in docs: 'less' vs 'fewer'
